# Generated by Django 3.0.8 on 2020-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_project', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('01-SSR', '01-SSR'), ('02-Test Plan', '02-Test Plan'), ('03-Weight & Balance', '03-Weight & Balance'), ('04-Electrical Load Analysis', '04-Electrical Load Analysis'), ('05-Process Specification', '05-Process Specification'), ('06-Certification Plan', '06-Certification Plan'), ('07-Sevice Bulletin', '07-Sevice Bulletin'), ('08-Standards', '08-Standards'), ('09-Engineering, Functional Hazard, Flamm', '09-Engineering, Functional Hazard, Flamm'), ('10-Manuals (IPC, CMM, AFMS..)', '10-Manuals (IPC, CMM, AFMS..)'), ('11-Kit Lists', '11-Kit Lists'), ('12-Airworthiness', '12-Airworthiness'), ('13-EO', '13-EO'), ('14-Miscellaneious (Performance)', '14-Miscellaneious (Performance)'), ('15-Compliance Reports', '15-Compliance Reports'), ('16-Regulatory Airworthiness Assessment (RAA)', '16-Regulatory Airworthiness Assessment (RAA)'), ('17-Drawing', '17-Drawing'), ('18-SolidWorks Model', '18-SolidWorks Model'), ('19-Research', '19-Research'), ('20-Training', '20-Training'), ('21-Other', '21-Other')], max_length=100)),
            ],
        ),
    ]
