# Generated by Django 3.0.8 on 2020-07-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_budgeted',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_manager',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work_order',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(choices=[('Alex Bojorquez', 'Alex Bojorquez'), ('Andrew Liang', 'Andrew Liang'), ('Angel Linares', 'Angel Linares'), ('Armando Fuentes', 'Armando Fuentes'), ('Chuck Burgan', 'Chuck Burgan'), ('Claudia Petrisor', 'Claudia Petrisor'), ('Diana Ngo', 'Diana Ngo'), ('Edgardo Perez', 'Edgardo Perez'), ('Francisco Valerio', 'Francisco Valerio'), ('Garrett Parham', 'Garrett Parham'), ('Gary Torres', 'Gary Torres'), ('Hien Tran', 'Hien Tran'), ('Jack Liu', 'Jack Liu'), ('Javier Hernandez', 'Javier Hernandez'), ('Jimmy Nguyen', 'Jimmy Nguyen'), ('Jonathan Prieto', 'Jonathan Prieto'), ('Marco Vargas', 'Marco Vargas'), ('Martin Hade', 'Martin Hade'), ('Michael Caputo', 'Michael Caputo'), ('Patrick Ashton', 'Patrick Ashton'), ('Peter Ngo', 'Peter Ngo'), ('Rasoul Hadady', 'Rasoul Hadady'), ('Tai Kieu', 'Tai Kieu'), ('Terry Gossett', 'Terry Gossett')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours_given',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('01-SSR', '01-SSR'), ('02-Test Plan', '02-Test Plan'), ('03-Weight & Balance', '03-Weight & Balance'), ('04-Electrical Load Analysis', '04-Electrical Load Analysis'), ('05-Process Specification', '05-Process Specification'), ('06-Certification Plan', '06-Certification Plan'), ('07-Sevice Bulletin', '07-Sevice Bulletin'), ('08-Standards', '08-Standards'), ('09-Engineering, Functional Hazard, Flamm', '09-Engineering, Functional Hazard, Flamm'), ('10-Manuals (IPC, CMM, AFMS..)', '10-Manuals (IPC, CMM, AFMS..)'), ('11-Kit Lists', '11-Kit Lists'), ('12-Airworthiness', '12-Airworthiness'), ('13-EO', '13-EO'), ('14-Miscellaneious (Performance)', '14-Miscellaneious (Performance)'), ('15-Compliance Reports', '15-Compliance Reports'), ('16-Regulatory Airworthiness Assessment (RAA)', '16-Regulatory Airworthiness Assessment (RAA)'), ('17-Drawing', '17-Drawing'), ('18-SolidWorks Model', '18-SolidWorks Model'), ('19-Research', '19-Research'), ('20-Training', '20-Training'), ('21-Other', '21-Other')], max_length=100, null=True),
        ),
    ]
