# Generated by Django 3.0.8 on 2020-07-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200714_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program_manager',
            field=models.CharField(choices=[('Alex Bojorquez', 'Alex Bojorquez'), ('Andrew Liang', 'Andrew Liang'), ('Angel Linares', 'Angel Linares'), ('Armando Fuentes', 'Armando Fuentes'), ('Chuck Burgan', 'Chuck Burgan'), ('Claudia Petrisor', 'Claudia Petrisor'), ('Diana Ngo', 'Diana Ngo'), ('Edgardo Perez', 'Edgardo Perez'), ('Francisco Valerio', 'Francisco Valerio'), ('Garrett Parham', 'Garrett Parham'), ('Gary Torres', 'Gary Torres'), ('Hien Tran', 'Hien Tran'), ('Jack Liu', 'Jack Liu'), ('Javier Hernandez', 'Javier Hernandez'), ('Jimmy Nguyen', 'Jimmy Nguyen'), ('Jonathan Prieto', 'Jonathan Prieto'), ('Marco Vargas', 'Marco Vargas'), ('Martin Hade', 'Martin Hade'), ('Michael Caputo', 'Michael Caputo'), ('Patrick Ashton', 'Patrick Ashton'), ('Peter Ngo', 'Peter Ngo'), ('Rasoul Hadady', 'Rasoul Hadady'), ('Tai Kieu', 'Tai Kieu'), ('Terry Gossett', 'Terry Gossett')], max_length=25, null=True),
        ),
    ]
