# Generated by Django 3.0.8 on 2020-07-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200721_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_no',
        ),
    ]
