# Generated by Django 3.0.8 on 2020-07-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_task_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_no',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
