# Generated by Django 3.0.8 on 2020-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200722_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours_remaining',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10000, null=True),
        ),
    ]
