# Generated by Django 3.0.8 on 2020-07-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200722_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hours_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
