# Generated by Django 3.0.8 on 2020-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200724_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True),
        ),
    ]
