# Generated by Django 3.0.8 on 2020-07-26 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_used_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
