# Generated by Django 3.0.8 on 2020-07-26 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_auto_20200725_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('01', '01-SSR'), ('02', '02-Test Plan'), ('03', '03-Weight & Balance'), ('04', '04-Electrical Load Analysis'), ('05', '05-Process Specification'), ('06', '06-Certification Plan'), ('07', '07-Sevice Bulletin'), ('08', '08-Standards'), ('09', '09-Engineering, Functional Hazard, Flamm'), ('10', '10-Manuals (IPC, CMM, AFMS..)'), ('11', '11-Kit Lists'), ('12', '12-Airworthiness'), ('13', '13-EO'), ('14', '14-Miscellaneious (Performance)'), ('15', '15-Compliance Reports'), ('16', '16-Regulatory Airworthiness Assessment (RAA)'), ('17', '17-Drawing'), ('18', '18-SolidWorks Model'), ('19', '19-Research'), ('20', '20-Training'), ('21', '21-Other')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('hours_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('hours_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('task_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Task')),
            ],
        ),
    ]
