# Generated by Django 3.0.8 on 2020-07-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200725_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day_used_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True),
        ),
    ]
