# Generated by Django 3.0.8 on 2020-07-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200727_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='hours_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.CreateModel(
            name='DailyLogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Task')),
            ],
        ),
    ]
